name: Publish Python 🐍 package to PyPI

on:
  push:
    tags:
      - "v*"   # triggers only on tags like v0.1.0, v1.0.2, etc.

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: pypi   # optional but matches the one you added in PyPI
    permissions:
      id-token: write  # required for trusted publishing
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }} # not used for trusted publishers, safe to leave out